#!/bin/sh

# this is the usage routine
usage()
{
  echo "$0 [-f|-s|-v] [-m <frame>] <video.xml>"
  echo
  echo "where:"
  echo "  <frame> is the optional maximum frame to render to"
  echo "  <video.xml> is the video XML file to render"
  echo "  -f: render only video frames"
  echo "  -s: render only sound"
  echo "  -v: render only video"
  echo
}

# figure out where our lib directory is
libdir=`dirname $0`/../lib

# if $1 is -f, then $2 is a frame number, and we shift off both of them
if [ "$1" = "-m" ]
then
  # check for a valid $2: if not, print usage and exit
  if [ -n "$2" ]
  then
    # check the frame field is an invalid number
    if echo $2 | grep -q -v "^[0-9]*$"
    then
      echo
      echo "error: argument for -m must be a number"
      echo
      usage
      exit 1
    fi

    # pull frame number out, shift off arguments
    maxframe="$2"
    maxframearg="-Dvcom.render.frame.maxframe=$maxframe"
    shift
    shift
  else
    # we didn't have a $2
    echo
    echo "error: must specify argument for -m"
    echo
    usage
    exit 1
  fi

  echo "Setting max frame to $maxframe"
fi

# if we have no arguments, show usage and exit
if [ -z "$1" ]
then
  echo
  echo "error: must specify video XML file to process"
  echo
  usage
  exit 1
fi

# generate the classpath
CLASSPATH=
for jar in $libdir/*
do
  CLASSPATH=$CLASSPATH:$jar
done

# increase max memory size
JAVA_OPTS="$JAVA_OPTS -Xmx512m"

# run vcom with the classpath and the passed arguments
#echo java $maxframearg $JAVA_OPTS -cp $CLASSPATH net.vcom.VComRender $*
java $maxframearg $JAVA_OPTS -cp $CLASSPATH net.vcom.VComRender $*
